-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        blur = {
            size = 7,
        },
    },
})

-- Bezier curves
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })
hl.curve("quick", { type = "bezier", points = { {0.15, 0.0}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 3.5,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "windows",
    enabled = false,
})
hl.animation({
    leaf = "windowsMove",
    enabled = false,
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 1.0,
    bezier = "quick",
})
