background {
    monitor =
    path = ~/Images/wallpaper/e2.jpg   
    blur_passes = 3                  # More passes means a smoother blur
    blur_size = 7                    # Higher number means stronger blur
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    fade_on_empty = false
    font_color = rgb(200, 200, 200)
    inner_color = rgb(20, 20, 25)
    outer_color = rgb(40, 40, 50)
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    placeholder_text = <i>Input Password...</i>
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big>$(date +'%H:%M')</big></b>"
    color = rgb(240, 240, 245)
    font_size = 64
    font_family = sans-serif
    position = 0, 120
    halign = center
    valign = center
}
